version: '3.8'

services:
  app:
    build: .
    container_name: araperful-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/araperful
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: araperful-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  mongo_data: